let API_URL = process.env.REACT_APP_SERVER_URL
let GOOGLE_ID = process.env.REACT_APP_GOOGLE_ID
let CHAT_URL = process.env.REACT_APP_CHAT_SERVER_URL
let BASE_URL = process.env.REACT_APP_SERVER_AND_PORT

export { API_URL, GOOGLE_ID, CHAT_URL, BASE_URL}